// SPDX-License-Identifier: GPL-3.0
// Generated by circuits/build.sh from deal_final.zkey (snarkjs 0.7.6). Do not edit.
// DEVELOPMENT SETUP (single local contribution + beacon): NOT FOR PRODUCTION.
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

pragma solidity >=0.7.0 <0.9.0;

contract DealVerifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data
    uint256 constant alphax  = 16428432848801857252194528405604668803277877773566238944394625302971855135431;
    uint256 constant alphay  = 16846502678714586896801519656441059708016666274385668027902869494772365009666;
    uint256 constant betax1  = 3182164110458002340215786955198810119980427837186618912744689678939861918171;
    uint256 constant betax2  = 16348171800823588416173124589066524623406261996681292662100840445103873053252;
    uint256 constant betay1  = 4920802715848186258981584729175884379674325733638798907835771393452862684714;
    uint256 constant betay2  = 19687132236965066906216944365591810874384658708175106803089633851114028275753;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 21015096074021241344292072025545878321868779369264830846133879572536457142300;
    uint256 constant deltax2 = 20877176979468884829519184071608009979059003476052282286380366981606162202341;
    uint256 constant deltay1 = 4910765718996215507202133346287333563220691474932194992988867197376759990240;
    uint256 constant deltay2 = 21252055708429970134926017558317893941157444680985141469193069992484918673944;

    
    uint256 constant IC0x = 1830218700346020786767348008492390579717171799010143096057143314895175544090;
    uint256 constant IC0y = 1721637724302253297907071887603460412192176501516342767995118730889797984775;
    
    uint256 constant IC1x = 9004084767292037698177190510190581114501927195487522784346106171199345616437;
    uint256 constant IC1y = 18321349984405949811230800277768728565526243561524117600477576673749728650135;
    
    uint256 constant IC2x = 8123549561538126688436571019732172546253069629746053252916413632538728509430;
    uint256 constant IC2y = 7929427109691613594881856994157499887493559098399858240843432323502300254534;
    
    uint256 constant IC3x = 10783495459072680168737946850182594361308190672090991932479470837829906572172;
    uint256 constant IC3y = 14523858158738748103866796210146470260104944327020078831627868619784649478727;
    
    uint256 constant IC4x = 7432908303327015372761030258104260468325303721656020025476482085375688219349;
    uint256 constant IC4y = 2625935761300866154757017709366528285262220260980454328647236036287097015474;
    
    uint256 constant IC5x = 8702426252094917751168814339277777026665986119351903075622958065076918261720;
    uint256 constant IC5y = 3090357774256944690576969837420818886405331744346646814690949101938180407907;
    
    uint256 constant IC6x = 14887137248394307555056340406644428831806689458015002109670069411376316674341;
    uint256 constant IC6y = 13569025966155115590954551922110593424002504146278142687075127772544063029755;
    
    uint256 constant IC7x = 14174220243123586006137894494108944765716665585341792436111837024023419402336;
    uint256 constant IC7y = 2769787706257112665216688543511225380336826279387089501513492517177442731840;
    
    uint256 constant IC8x = 2017139068397262593727298909726098084378778202874408215666481036749189507430;
    uint256 constant IC8y = 9926222144004142815548029526703975119782604263991062244566139824371797989354;
    
    uint256 constant IC9x = 12020991087715507418122206870001357457313258452254993253980431385452010994289;
    uint256 constant IC9y = 19978979326979402112744117685064268422382743639935194816109537785164287562234;
    
    uint256 constant IC10x = 15321822963228771586958766295084264802930451548663341980431213285109206721584;
    uint256 constant IC10y = 2078575670601193873419453058137935828133874496949488527489999109129395192868;
    
    uint256 constant IC11x = 20445898674771795146156818180701840405868808234632928033463972840384333315214;
    uint256 constant IC11y = 21727000416461770195801567024473682774411701779733994563417825013853699437453;
    
    uint256 constant IC12x = 13050037268967695885235334002159492179611736796397689425248391703024502800079;
    uint256 constant IC12y = 15720216253501435680329308588485720140269533931589793983051509312710190945587;
    
    uint256 constant IC13x = 20076440470786603200044350897714119223725140589823517272223896205460515152557;
    uint256 constant IC13y = 7388876781116782146874774835178597482381732083659792506706699483621013690137;
    
    uint256 constant IC14x = 3637223205377200837854565202170568160601225500409985136240924458726691449113;
    uint256 constant IC14y = 3369994561843787646985818632288843218753182709835924678716200393912724231041;
    
    uint256 constant IC15x = 1615300324672946739486974091869124130565839143654136686627962891285189427136;
    uint256 constant IC15y = 5060526087455748187963394708253163258357442970202013621593593751298363319989;
    
    uint256 constant IC16x = 9586471875697933902943310176950055991295648306681514653884768141774406259905;
    uint256 constant IC16y = 3387311787897675348901470463102568311701304015086472604253070658704159811445;
    
    uint256 constant IC17x = 5006249445573915537768947994345011793946540545148526265719624549740545471850;
    uint256 constant IC17y = 3689300321785917782232649091976860932520104804580273100914130688010908494760;
    
    uint256 constant IC18x = 10210228150044126869769360937734728589613336064624456669155016529540719254631;
    uint256 constant IC18y = 949401102314350782760269222339940297501374188337925156839426327882789593767;
    
    uint256 constant IC19x = 2101919391562916047155639571322609081638933437372520278465197748366301889957;
    uint256 constant IC19y = 18770339194536282265948807171235524149220438932213996952147229000032694192700;
    
    uint256 constant IC20x = 21736655897194218646610391057937348747474260510209832615728274900213911475409;
    uint256 constant IC20y = 3164790902163967979690475561395941264758603823066207142710995612139514827919;
    
    uint256 constant IC21x = 15049947331585082431211829031405433616676584757449893875318438722367896113627;
    uint256 constant IC21y = 14061316274253537292051202080207551729289176662401360588897410677760815038258;
    
    uint256 constant IC22x = 19400748226138384231616476634004472241935577703904382744517721679943672731488;
    uint256 constant IC22y = 21876952062694491047916491319677143522133399004302287906582640080934982351638;
    
    uint256 constant IC23x = 7799827353404051292132063636735024534043209898317329768793685513024528024594;
    uint256 constant IC23y = 856823442803082375755111796916912310738616267835180836842015007919444986699;
    
    uint256 constant IC24x = 14451806027538674139081400915933407508625083898370534313874481777637831414413;
    uint256 constant IC24y = 15625870114748802346999917354877699229476296705019063797145072831746316543763;
    
    uint256 constant IC25x = 15656117854332459884734076247687457654001957089290820518862960899804294186772;
    uint256 constant IC25y = 19452755812060738802205254201596135387475497179308208290326232494191750129512;
    
    uint256 constant IC26x = 13934012024942406641575663222125795619741088502956976916918034598747828846297;
    uint256 constant IC26y = 11162911212868031648352971647506385772124709650520872295871058343530175149872;
    
    uint256 constant IC27x = 5449756276257181747149905848209141017858944378112567371315663644750999552498;
    uint256 constant IC27y = 4927663982897101862082224811127748542844205732778486158932247927559250754515;
    
    uint256 constant IC28x = 5792698499943487620107431439716438916370089249199872369871940390873942860266;
    uint256 constant IC28y = 9604902018107072351443941645347811807867887559180519355030025789090577310884;
    
    uint256 constant IC29x = 21327428880039220380259133206197389573677718272454860497358789513295502362326;
    uint256 constant IC29y = 7230959220151370292208729961407111973541843353471909410940719956460304162987;
    
    uint256 constant IC30x = 19690365429446421867210939637370892021397367283669631641683094797390816208726;
    uint256 constant IC30y = 16735519059215566324371833920907331175685085239551917974479528434064414359210;
    
    uint256 constant IC31x = 5043208770179857242589150685615570899114339573092176938521927171597955107345;
    uint256 constant IC31y = 14414848153443144373801262009523024994372051937648524198906148444549787281937;
    
    uint256 constant IC32x = 19743521784173520233037152216455835713165511263753279427324957300259720844471;
    uint256 constant IC32y = 2009794277040546306797119626638251412011173008852209193361286626782391255091;
    
    uint256 constant IC33x = 14529930878799920233360459436770047003173302980020407381806075779488477144119;
    uint256 constant IC33y = 5785114947783948542309906884463865182178217043450335462040039500046067497446;
    
    uint256 constant IC34x = 12965520665619723284719896486798248495492370054173901064688392628053854958815;
    uint256 constant IC34y = 13893109037226433211414876175231629741880639291248366313573281515364171018460;
    
    uint256 constant IC35x = 1410234825128186000621337767763347061011859166920347220769601898836525327109;
    uint256 constant IC35y = 6190527275988578690744828482960205677384036230586013239552996850130142483189;
    
    uint256 constant IC36x = 12806825004157415333637525835318247639271691695952210146589508322905859096558;
    uint256 constant IC36y = 7730538865390013907263563277051653018161709043725746640672442001810656722004;
    
    uint256 constant IC37x = 18051477277703526449841988725161665121265900245473860522993040944724501936447;
    uint256 constant IC37y = 5476064077335281304266833321783529686101840622353553696796821763561458682915;
    
    uint256 constant IC38x = 4140624755513609386645977026203590912826750729033093253311822783764300676214;
    uint256 constant IC38y = 1126135383436082569372500800138053005081555329230619245090389097592237394357;
    
    uint256 constant IC39x = 415191378439808072713337439559446014408473738671745290166487038270110892752;
    uint256 constant IC39y = 15426646014329784294982879812126504129086430359844945442333754246505174131949;
    
    uint256 constant IC40x = 15917534367094173873953864164204882729705313736049815137856741959646005854715;
    uint256 constant IC40y = 9563765702410155727414946967712425042292493976913769402959249469686314409943;
    
    uint256 constant IC41x = 3358421730246686645335090661803353730180865727572663818751082254388210497188;
    uint256 constant IC41y = 16847794049896469413046390197115117564343578688847145659495099969797449200850;
    
    uint256 constant IC42x = 14071421908544262211820189988347055642071161019104203619302055776543135069493;
    uint256 constant IC42y = 9426450771466638347247605882489377742778906467609748254868044440441037558485;
    
    uint256 constant IC43x = 767454231272448104052134326267801315939489322673625733402328813110399224183;
    uint256 constant IC43y = 5486041976639039591482964045357770242784425056511835547004946396924485923773;
    
    uint256 constant IC44x = 15130159434838756697785768306528953245222020271250059513953344358587640200837;
    uint256 constant IC44y = 4235598863107110121183926636307565276889853111448787821479417344484187044996;
    
    uint256 constant IC45x = 3367292983769820013322756907597305961151297616147238563880244825057751263211;
    uint256 constant IC45y = 5613867938298832645010382734579692979250756595136731943353121521611252237110;
    
    uint256 constant IC46x = 13758816730984632760604037033794651619864513941925428564671531670782886998974;
    uint256 constant IC46y = 4992057626009251547756824568993913639302371644303280800745143449223902544524;
    
    uint256 constant IC47x = 13295204088428688659531339855860373413911882913214057281554747528093160783856;
    uint256 constant IC47y = 18213539716151022296010542015664367301978140752365143650847015135274041263559;
    
    uint256 constant IC48x = 7551295029561763411533227705810743581759479532216305381612448427457416312542;
    uint256 constant IC48y = 11372102437922300573287869140403256319094202080923643310505893046410772407264;
    
    uint256 constant IC49x = 10137574808531096749926054964957500452928317148681781677049062646775785180780;
    uint256 constant IC49y = 439910571673893647965128616514166512696771436364654132963149439444882044129;
    
    uint256 constant IC50x = 18329943558647851370731998574262926752685464990264979833960841475876978941460;
    uint256 constant IC50y = 11446271477517729858284687132483072737766068968974483909826646874517239745619;
    
    uint256 constant IC51x = 19003402595018310019788770376609837040083303037317632460791751412526948419797;
    uint256 constant IC51y = 6008840360455888720691370078556350711572652783086662413923332726390333817139;
    
    uint256 constant IC52x = 8613332083855834768787887092979068510181443111160674226472296460500943433210;
    uint256 constant IC52y = 15518819857545220888148438546986778922558072001128960714174378316196312217999;
    
    uint256 constant IC53x = 11008757960309296761802321596728529782082082116300407714737472396280713304585;
    uint256 constant IC53y = 11714514240641922109690217258955115186801060204780722612398859878035399952592;
    
    uint256 constant IC54x = 12919078226207146294822144948048673956331603050522097741790448818408855830390;
    uint256 constant IC54y = 17411140814030863911751370330464874981258560195952920573967981270601606013961;
    
    uint256 constant IC55x = 19306893132532600283368131319579326094249543526262549232497605815671927457951;
    uint256 constant IC55y = 1619162886033720353796810205099764631171121642720851202469136293549801275700;
    
    uint256 constant IC56x = 20561651678714221186874252367222528404392331037336244330767255213671928667668;
    uint256 constant IC56y = 17160540604381777385253934586312991944930189968911381436897944830151508733175;
    
    uint256 constant IC57x = 15774020587839526167052079098269302078206319177756953445377841077042858860245;
    uint256 constant IC57y = 7569400140694898775207432598505272687958406236402896776893929421849080677681;
    
    uint256 constant IC58x = 21184277277870243347666710782005372124805780634822171126131075862023928142961;
    uint256 constant IC58y = 17723791293212677651702730217884092323498751529749167379737805129397286474039;
    
    uint256 constant IC59x = 1222898110567916945466808663729779876364940501597736583558354946832384711149;
    uint256 constant IC59y = 8421493405094045903362692802715508951150715638787297945027103887980785743449;
    
    uint256 constant IC60x = 12047500251952684060915206112715679482488254938341476369258731865430419003441;
    uint256 constant IC60y = 10456041247946791139277818832727588555906309575821860660509851743731392138350;
    
    uint256 constant IC61x = 10275175291836851625727089943617664364924216440321634788487169482227523878204;
    uint256 constant IC61y = 6001036244607112651929351730902340250236060462841511322038783073651809566606;
    
    uint256 constant IC62x = 11294350945895718595331283343432603707328143162982543940714310987103684584203;
    uint256 constant IC62y = 4363939113063438560844229909996503438940918711775786558247293030738198586498;
    
    uint256 constant IC63x = 12594968293947960465556680848534084519667789139369976890347796709223043439146;
    uint256 constant IC63y = 7571281512537803898953408637948809326916480677104830456764558442229627412406;
    
    uint256 constant IC64x = 3859046361625833184107015475601624118197764047904252593566218742848378522003;
    uint256 constant IC64y = 16265732278717476121770132768232821747648603452749890109925782533698044042864;
    
    uint256 constant IC65x = 11066751456076530418104543053061681063857125317563745537861405893828104326684;
    uint256 constant IC65y = 11646516726512404488711081172874355828538841344962190015397641741646272063827;
    
    uint256 constant IC66x = 20310188737987288253065315988980694438308847211391775378921500016608911208296;
    uint256 constant IC66y = 11383968952568985304653612597572221902268199119903155166864529481617361318242;
    
    uint256 constant IC67x = 13717234868260351892883629903971140023955573527071522036008171162269327651963;
    uint256 constant IC67y = 14663821757193199771589475623961772242791811257331181761422951518680078066782;
    
    uint256 constant IC68x = 9155574770086325621825520982344547447854096850031187514296906826203453746483;
    uint256 constant IC68y = 11417919701094938382108061860308996780752260625116425027039861519372704476603;
    
    uint256 constant IC69x = 6966621064597478008241344246512182974453430380476770837390407606430574119576;
    uint256 constant IC69y = 4219366234586496381096904690290817314046859000920626217119412006852821116350;
    
    uint256 constant IC70x = 3288742801236130590751264204987940982657350173244524477036743752848132845690;
    uint256 constant IC70y = 3441500673945255636438952414962599298393443456738579534635188119622950777183;
    
    uint256 constant IC71x = 9868031996770155089387296488877106516817853532742827481747671893539767577198;
    uint256 constant IC71y = 14896984968987201535940283621792017633744763963945233408528063943884659468727;
    
    uint256 constant IC72x = 6802775049348811403244308936448531820458822698468829645932678101737439356981;
    uint256 constant IC72y = 3853869420224596284222536850815625243543186454666282551562782606194378582033;
    
    uint256 constant IC73x = 14469578136054879395344775930613592976838130015786846786018075081992955000281;
    uint256 constant IC73y = 8333675519079447050189860748150561157835370130529393499762070185365597007411;
    
    uint256 constant IC74x = 3450170169208406442380085671728421782939994000876454982948075141656751468586;
    uint256 constant IC74y = 9205756607463124548669959827309785203274904041139512236184840219906474838227;
    
    uint256 constant IC75x = 18268193865402206345498803231001426899618323915162993999188715658280450006297;
    uint256 constant IC75y = 21727301549035021483635551027239285483074587766968570441099711355346002326990;
    
    uint256 constant IC76x = 3255003122640075304026845822170187680020452981709269194581153685701495130923;
    uint256 constant IC76y = 2288257687328844916964203362578277367518611781599080365567133362439117163559;
    
    uint256 constant IC77x = 11590162174211355184968558811431009913937526619122024244369365356176194852643;
    uint256 constant IC77y = 6250934040394462030899473853850383685218005792075780456368660419843166989229;
    
    uint256 constant IC78x = 21647378072862408137230420560889801422167272187977099364543505320113182898361;
    uint256 constant IC78y = 18765672947934918430790697960947211508519977414171730564555906328709268213225;
    
    uint256 constant IC79x = 2945867194180752964937717202287019948624915692176601652868296890366810079437;
    uint256 constant IC79y = 11357909411222993307098425552402665220363220575850955506799537947854802504412;
    
    uint256 constant IC80x = 12977516550859484470977492039676493235525444953399388191917007244130863777467;
    uint256 constant IC80y = 19348918427666653402710929950610986935104948627892456539184727868969708256566;
    
    uint256 constant IC81x = 15506876953573997772769109153149694140290075178692275388201984325311547015984;
    uint256 constant IC81y = 17750526163015161512695427648229332237379063759712244828286540540840261682824;
    
    uint256 constant IC82x = 1414156180241871825972311725396276843331502101045599617903207780857179335491;
    uint256 constant IC82y = 6171222796957493150344257388467656340928084697030847814074577101788311227291;
    
    uint256 constant IC83x = 17013786949880695296721280555235744422729983289108044479336868414308431172257;
    uint256 constant IC83y = 18062953667970837538988923523865511046081092177005729923740210989725578348750;
    
    uint256 constant IC84x = 15681235769388988000784686287350940687396347951295920190451930627302480262687;
    uint256 constant IC84y = 7892592494527948346477021555928031638871616724351696483901853449369462761054;
    
    uint256 constant IC85x = 7227862649701296984494597300647408406783994424317320340160967367615196009820;
    uint256 constant IC85y = 5249627785859979259339758234970065150689725479509151890456081815815930757107;
    
    uint256 constant IC86x = 10408312141961094111161263678032924134457072579398454757195295390542359120788;
    uint256 constant IC86y = 4935911698771070758322200062117139937760397610408106348469582478847692390716;
    
    uint256 constant IC87x = 112754337017208915332647575441907691940109961571534381003526216254815222020;
    uint256 constant IC87y = 21823673995172354169298696479316252186495926236594321186184500974974864527390;
    
 
    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant pLastMem = 896;

    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[87] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }
            
            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                
                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                
                g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                
                g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                
                g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                
                g1_mulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                
                g1_mulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                
                g1_mulAccC(_pVk, IC11x, IC11y, calldataload(add(pubSignals, 320)))
                
                g1_mulAccC(_pVk, IC12x, IC12y, calldataload(add(pubSignals, 352)))
                
                g1_mulAccC(_pVk, IC13x, IC13y, calldataload(add(pubSignals, 384)))
                
                g1_mulAccC(_pVk, IC14x, IC14y, calldataload(add(pubSignals, 416)))
                
                g1_mulAccC(_pVk, IC15x, IC15y, calldataload(add(pubSignals, 448)))
                
                g1_mulAccC(_pVk, IC16x, IC16y, calldataload(add(pubSignals, 480)))
                
                g1_mulAccC(_pVk, IC17x, IC17y, calldataload(add(pubSignals, 512)))
                
                g1_mulAccC(_pVk, IC18x, IC18y, calldataload(add(pubSignals, 544)))
                
                g1_mulAccC(_pVk, IC19x, IC19y, calldataload(add(pubSignals, 576)))
                
                g1_mulAccC(_pVk, IC20x, IC20y, calldataload(add(pubSignals, 608)))
                
                g1_mulAccC(_pVk, IC21x, IC21y, calldataload(add(pubSignals, 640)))
                
                g1_mulAccC(_pVk, IC22x, IC22y, calldataload(add(pubSignals, 672)))
                
                g1_mulAccC(_pVk, IC23x, IC23y, calldataload(add(pubSignals, 704)))
                
                g1_mulAccC(_pVk, IC24x, IC24y, calldataload(add(pubSignals, 736)))
                
                g1_mulAccC(_pVk, IC25x, IC25y, calldataload(add(pubSignals, 768)))
                
                g1_mulAccC(_pVk, IC26x, IC26y, calldataload(add(pubSignals, 800)))
                
                g1_mulAccC(_pVk, IC27x, IC27y, calldataload(add(pubSignals, 832)))
                
                g1_mulAccC(_pVk, IC28x, IC28y, calldataload(add(pubSignals, 864)))
                
                g1_mulAccC(_pVk, IC29x, IC29y, calldataload(add(pubSignals, 896)))
                
                g1_mulAccC(_pVk, IC30x, IC30y, calldataload(add(pubSignals, 928)))
                
                g1_mulAccC(_pVk, IC31x, IC31y, calldataload(add(pubSignals, 960)))
                
                g1_mulAccC(_pVk, IC32x, IC32y, calldataload(add(pubSignals, 992)))
                
                g1_mulAccC(_pVk, IC33x, IC33y, calldataload(add(pubSignals, 1024)))
                
                g1_mulAccC(_pVk, IC34x, IC34y, calldataload(add(pubSignals, 1056)))
                
                g1_mulAccC(_pVk, IC35x, IC35y, calldataload(add(pubSignals, 1088)))
                
                g1_mulAccC(_pVk, IC36x, IC36y, calldataload(add(pubSignals, 1120)))
                
                g1_mulAccC(_pVk, IC37x, IC37y, calldataload(add(pubSignals, 1152)))
                
                g1_mulAccC(_pVk, IC38x, IC38y, calldataload(add(pubSignals, 1184)))
                
                g1_mulAccC(_pVk, IC39x, IC39y, calldataload(add(pubSignals, 1216)))
                
                g1_mulAccC(_pVk, IC40x, IC40y, calldataload(add(pubSignals, 1248)))
                
                g1_mulAccC(_pVk, IC41x, IC41y, calldataload(add(pubSignals, 1280)))
                
                g1_mulAccC(_pVk, IC42x, IC42y, calldataload(add(pubSignals, 1312)))
                
                g1_mulAccC(_pVk, IC43x, IC43y, calldataload(add(pubSignals, 1344)))
                
                g1_mulAccC(_pVk, IC44x, IC44y, calldataload(add(pubSignals, 1376)))
                
                g1_mulAccC(_pVk, IC45x, IC45y, calldataload(add(pubSignals, 1408)))
                
                g1_mulAccC(_pVk, IC46x, IC46y, calldataload(add(pubSignals, 1440)))
                
                g1_mulAccC(_pVk, IC47x, IC47y, calldataload(add(pubSignals, 1472)))
                
                g1_mulAccC(_pVk, IC48x, IC48y, calldataload(add(pubSignals, 1504)))
                
                g1_mulAccC(_pVk, IC49x, IC49y, calldataload(add(pubSignals, 1536)))
                
                g1_mulAccC(_pVk, IC50x, IC50y, calldataload(add(pubSignals, 1568)))
                
                g1_mulAccC(_pVk, IC51x, IC51y, calldataload(add(pubSignals, 1600)))
                
                g1_mulAccC(_pVk, IC52x, IC52y, calldataload(add(pubSignals, 1632)))
                
                g1_mulAccC(_pVk, IC53x, IC53y, calldataload(add(pubSignals, 1664)))
                
                g1_mulAccC(_pVk, IC54x, IC54y, calldataload(add(pubSignals, 1696)))
                
                g1_mulAccC(_pVk, IC55x, IC55y, calldataload(add(pubSignals, 1728)))
                
                g1_mulAccC(_pVk, IC56x, IC56y, calldataload(add(pubSignals, 1760)))
                
                g1_mulAccC(_pVk, IC57x, IC57y, calldataload(add(pubSignals, 1792)))
                
                g1_mulAccC(_pVk, IC58x, IC58y, calldataload(add(pubSignals, 1824)))
                
                g1_mulAccC(_pVk, IC59x, IC59y, calldataload(add(pubSignals, 1856)))
                
                g1_mulAccC(_pVk, IC60x, IC60y, calldataload(add(pubSignals, 1888)))
                
                g1_mulAccC(_pVk, IC61x, IC61y, calldataload(add(pubSignals, 1920)))
                
                g1_mulAccC(_pVk, IC62x, IC62y, calldataload(add(pubSignals, 1952)))
                
                g1_mulAccC(_pVk, IC63x, IC63y, calldataload(add(pubSignals, 1984)))
                
                g1_mulAccC(_pVk, IC64x, IC64y, calldataload(add(pubSignals, 2016)))
                
                g1_mulAccC(_pVk, IC65x, IC65y, calldataload(add(pubSignals, 2048)))
                
                g1_mulAccC(_pVk, IC66x, IC66y, calldataload(add(pubSignals, 2080)))
                
                g1_mulAccC(_pVk, IC67x, IC67y, calldataload(add(pubSignals, 2112)))
                
                g1_mulAccC(_pVk, IC68x, IC68y, calldataload(add(pubSignals, 2144)))
                
                g1_mulAccC(_pVk, IC69x, IC69y, calldataload(add(pubSignals, 2176)))
                
                g1_mulAccC(_pVk, IC70x, IC70y, calldataload(add(pubSignals, 2208)))
                
                g1_mulAccC(_pVk, IC71x, IC71y, calldataload(add(pubSignals, 2240)))
                
                g1_mulAccC(_pVk, IC72x, IC72y, calldataload(add(pubSignals, 2272)))
                
                g1_mulAccC(_pVk, IC73x, IC73y, calldataload(add(pubSignals, 2304)))
                
                g1_mulAccC(_pVk, IC74x, IC74y, calldataload(add(pubSignals, 2336)))
                
                g1_mulAccC(_pVk, IC75x, IC75y, calldataload(add(pubSignals, 2368)))
                
                g1_mulAccC(_pVk, IC76x, IC76y, calldataload(add(pubSignals, 2400)))
                
                g1_mulAccC(_pVk, IC77x, IC77y, calldataload(add(pubSignals, 2432)))
                
                g1_mulAccC(_pVk, IC78x, IC78y, calldataload(add(pubSignals, 2464)))
                
                g1_mulAccC(_pVk, IC79x, IC79y, calldataload(add(pubSignals, 2496)))
                
                g1_mulAccC(_pVk, IC80x, IC80y, calldataload(add(pubSignals, 2528)))
                
                g1_mulAccC(_pVk, IC81x, IC81y, calldataload(add(pubSignals, 2560)))
                
                g1_mulAccC(_pVk, IC82x, IC82y, calldataload(add(pubSignals, 2592)))
                
                g1_mulAccC(_pVk, IC83x, IC83y, calldataload(add(pubSignals, 2624)))
                
                g1_mulAccC(_pVk, IC84x, IC84y, calldataload(add(pubSignals, 2656)))
                
                g1_mulAccC(_pVk, IC85x, IC85y, calldataload(add(pubSignals, 2688)))
                
                g1_mulAccC(_pVk, IC86x, IC86y, calldataload(add(pubSignals, 2720)))
                
                g1_mulAccC(_pVk, IC87x, IC87y, calldataload(add(pubSignals, 2752)))
                

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))


                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)


                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F
            
            checkField(calldataload(add(_pubSignals, 0)))
            
            checkField(calldataload(add(_pubSignals, 32)))
            
            checkField(calldataload(add(_pubSignals, 64)))
            
            checkField(calldataload(add(_pubSignals, 96)))
            
            checkField(calldataload(add(_pubSignals, 128)))
            
            checkField(calldataload(add(_pubSignals, 160)))
            
            checkField(calldataload(add(_pubSignals, 192)))
            
            checkField(calldataload(add(_pubSignals, 224)))
            
            checkField(calldataload(add(_pubSignals, 256)))
            
            checkField(calldataload(add(_pubSignals, 288)))
            
            checkField(calldataload(add(_pubSignals, 320)))
            
            checkField(calldataload(add(_pubSignals, 352)))
            
            checkField(calldataload(add(_pubSignals, 384)))
            
            checkField(calldataload(add(_pubSignals, 416)))
            
            checkField(calldataload(add(_pubSignals, 448)))
            
            checkField(calldataload(add(_pubSignals, 480)))
            
            checkField(calldataload(add(_pubSignals, 512)))
            
            checkField(calldataload(add(_pubSignals, 544)))
            
            checkField(calldataload(add(_pubSignals, 576)))
            
            checkField(calldataload(add(_pubSignals, 608)))
            
            checkField(calldataload(add(_pubSignals, 640)))
            
            checkField(calldataload(add(_pubSignals, 672)))
            
            checkField(calldataload(add(_pubSignals, 704)))
            
            checkField(calldataload(add(_pubSignals, 736)))
            
            checkField(calldataload(add(_pubSignals, 768)))
            
            checkField(calldataload(add(_pubSignals, 800)))
            
            checkField(calldataload(add(_pubSignals, 832)))
            
            checkField(calldataload(add(_pubSignals, 864)))
            
            checkField(calldataload(add(_pubSignals, 896)))
            
            checkField(calldataload(add(_pubSignals, 928)))
            
            checkField(calldataload(add(_pubSignals, 960)))
            
            checkField(calldataload(add(_pubSignals, 992)))
            
            checkField(calldataload(add(_pubSignals, 1024)))
            
            checkField(calldataload(add(_pubSignals, 1056)))
            
            checkField(calldataload(add(_pubSignals, 1088)))
            
            checkField(calldataload(add(_pubSignals, 1120)))
            
            checkField(calldataload(add(_pubSignals, 1152)))
            
            checkField(calldataload(add(_pubSignals, 1184)))
            
            checkField(calldataload(add(_pubSignals, 1216)))
            
            checkField(calldataload(add(_pubSignals, 1248)))
            
            checkField(calldataload(add(_pubSignals, 1280)))
            
            checkField(calldataload(add(_pubSignals, 1312)))
            
            checkField(calldataload(add(_pubSignals, 1344)))
            
            checkField(calldataload(add(_pubSignals, 1376)))
            
            checkField(calldataload(add(_pubSignals, 1408)))
            
            checkField(calldataload(add(_pubSignals, 1440)))
            
            checkField(calldataload(add(_pubSignals, 1472)))
            
            checkField(calldataload(add(_pubSignals, 1504)))
            
            checkField(calldataload(add(_pubSignals, 1536)))
            
            checkField(calldataload(add(_pubSignals, 1568)))
            
            checkField(calldataload(add(_pubSignals, 1600)))
            
            checkField(calldataload(add(_pubSignals, 1632)))
            
            checkField(calldataload(add(_pubSignals, 1664)))
            
            checkField(calldataload(add(_pubSignals, 1696)))
            
            checkField(calldataload(add(_pubSignals, 1728)))
            
            checkField(calldataload(add(_pubSignals, 1760)))
            
            checkField(calldataload(add(_pubSignals, 1792)))
            
            checkField(calldataload(add(_pubSignals, 1824)))
            
            checkField(calldataload(add(_pubSignals, 1856)))
            
            checkField(calldataload(add(_pubSignals, 1888)))
            
            checkField(calldataload(add(_pubSignals, 1920)))
            
            checkField(calldataload(add(_pubSignals, 1952)))
            
            checkField(calldataload(add(_pubSignals, 1984)))
            
            checkField(calldataload(add(_pubSignals, 2016)))
            
            checkField(calldataload(add(_pubSignals, 2048)))
            
            checkField(calldataload(add(_pubSignals, 2080)))
            
            checkField(calldataload(add(_pubSignals, 2112)))
            
            checkField(calldataload(add(_pubSignals, 2144)))
            
            checkField(calldataload(add(_pubSignals, 2176)))
            
            checkField(calldataload(add(_pubSignals, 2208)))
            
            checkField(calldataload(add(_pubSignals, 2240)))
            
            checkField(calldataload(add(_pubSignals, 2272)))
            
            checkField(calldataload(add(_pubSignals, 2304)))
            
            checkField(calldataload(add(_pubSignals, 2336)))
            
            checkField(calldataload(add(_pubSignals, 2368)))
            
            checkField(calldataload(add(_pubSignals, 2400)))
            
            checkField(calldataload(add(_pubSignals, 2432)))
            
            checkField(calldataload(add(_pubSignals, 2464)))
            
            checkField(calldataload(add(_pubSignals, 2496)))
            
            checkField(calldataload(add(_pubSignals, 2528)))
            
            checkField(calldataload(add(_pubSignals, 2560)))
            
            checkField(calldataload(add(_pubSignals, 2592)))
            
            checkField(calldataload(add(_pubSignals, 2624)))
            
            checkField(calldataload(add(_pubSignals, 2656)))
            
            checkField(calldataload(add(_pubSignals, 2688)))
            
            checkField(calldataload(add(_pubSignals, 2720)))
            
            checkField(calldataload(add(_pubSignals, 2752)))
            

            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
             return(0, 0x20)
         }
     }
 }
