// SPDX-License-Identifier: GPL-3.0
// Generated by circuits/build.sh from partial_final.zkey (snarkjs 0.7.6). Do not edit.
// DEVELOPMENT SETUP (single local contribution + beacon): NOT FOR PRODUCTION.
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

pragma solidity >=0.7.0 <0.9.0;

contract PartialVerifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data
    uint256 constant alphax  = 16428432848801857252194528405604668803277877773566238944394625302971855135431;
    uint256 constant alphay  = 16846502678714586896801519656441059708016666274385668027902869494772365009666;
    uint256 constant betax1  = 3182164110458002340215786955198810119980427837186618912744689678939861918171;
    uint256 constant betax2  = 16348171800823588416173124589066524623406261996681292662100840445103873053252;
    uint256 constant betay1  = 4920802715848186258981584729175884379674325733638798907835771393452862684714;
    uint256 constant betay2  = 19687132236965066906216944365591810874384658708175106803089633851114028275753;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 13388837573975425546803669117056385795220372787620257729020870589490327896610;
    uint256 constant deltax2 = 9120701351988308788159973230948531558924749450890011301720189981908739227101;
    uint256 constant deltay1 = 14609505362561352603533811320661262730770345215225801626520152682919182278726;
    uint256 constant deltay2 = 20752361737620332607258574190520661287359152567657911255082304535307078460453;

    
    uint256 constant IC0x = 7091488259845111192252887947194397711914548428182952002683832135262666839817;
    uint256 constant IC0y = 21089392964199314084279857159733248964116135788597151721999925684405929022925;
    
    uint256 constant IC1x = 11434098314733417684591631702193420724784089545446138760753194305029387661670;
    uint256 constant IC1y = 14086376207047480441041834957177910859128068616579063002707907781863852881509;
    
    uint256 constant IC2x = 13434474738479959497244494178342748004942750920587219240890131714508950938487;
    uint256 constant IC2y = 9810849781922570596130681547336533949266855046341666343370321420612875583114;
    
    uint256 constant IC3x = 8368969900266437798799029332952569443935276641731625771527501241201723719524;
    uint256 constant IC3y = 2516681049329311956252983768115062653563041443008756743103603009722473157943;
    
    uint256 constant IC4x = 11489905313318691705855866374158113947082022589326724679790837819304594770034;
    uint256 constant IC4y = 16009194655721383875951280789419969396125927402921248906501887915477845128262;
    
    uint256 constant IC5x = 7491498963736212977901668422605584974165704569952594310853300123210557391706;
    uint256 constant IC5y = 16412535754820114331015027572526704264064439323262057514390734200081026032899;
    
    uint256 constant IC6x = 18050555262368642416698034848464886366560131220686769018568947920746967179144;
    uint256 constant IC6y = 13728540713135151841720055267729013560779545713164316629962336101504075549761;
    
    uint256 constant IC7x = 7353449436420055533496450675262620911160728494931316048972034870630311634925;
    uint256 constant IC7y = 15729837703447248689181461736163513146540395849113337068736871439031779788952;
    
    uint256 constant IC8x = 6951103310276508599412557789618285643337914570974754794370940419216974980016;
    uint256 constant IC8y = 13923584286046206751254805452635871086558728764577315257032166740162853552091;
    
    uint256 constant IC9x = 13764679679160964380727740083614919139951873415705218402897415097697641703628;
    uint256 constant IC9y = 5858123954376815034307359365474398915995746482484959464989027511569685500931;
    
    uint256 constant IC10x = 5386966703535974777759803560679706573771931772077905116205236910965085476791;
    uint256 constant IC10y = 18831402035916060386378925235636497936816189368871723882006555660803471894649;
    
    uint256 constant IC11x = 5136988872283818365584066698002969242527843706765546550291714856712009969668;
    uint256 constant IC11y = 10298358858061702076112842692515230978284366989907198276596563191168136081356;
    
    uint256 constant IC12x = 3538758822463159532264643776398421223548437888734788101574916755289448263768;
    uint256 constant IC12y = 5554604877536968528409658462918541730534382834390280526693495198241144283321;
    
    uint256 constant IC13x = 3975975334885041029728287428598889075738894051318049115371956230719299243281;
    uint256 constant IC13y = 6507454716829565231948925835712924817018155121647092552927016771478743222547;
    
    uint256 constant IC14x = 14069940337556119763726007485497846972806805527673095657192084535618713471335;
    uint256 constant IC14y = 12075567739412196961683975446407664293218942523815600706397698474912860890464;
    
    uint256 constant IC15x = 14920443313677167950071081506313651207250749753659513059368778741712278434012;
    uint256 constant IC15y = 20171714648309623200652270176618163133008249924178758956854288724305701236941;
    
    uint256 constant IC16x = 8728119448680606994887838299735086984470648386028514352925400218167426002445;
    uint256 constant IC16y = 2109311728363931418311095049187382966113781252055761179232431170994104741806;
    
    uint256 constant IC17x = 12046235722123656100836079697012987181858656856249133575225329696495224978538;
    uint256 constant IC17y = 5701279738086729763245250912946521046832477469472878503798659754526407606402;
    
    uint256 constant IC18x = 3030502520870943958582261887258384800775696072866019393308753472147352705333;
    uint256 constant IC18y = 4385334639713407431057541437860225584028332584053265091106709245786249776240;
    
    uint256 constant IC19x = 19709505038885626703447188677085755541823831654397065351272595623256607783194;
    uint256 constant IC19y = 21319098752824754809453317319135659709367714784371580706497666322217574194539;
    
    uint256 constant IC20x = 16180192420295866405909239992915412723479684033543304484333984809233219317003;
    uint256 constant IC20y = 17524552050805047109445092574112007683851224570779664852474691778390311537202;
    
    uint256 constant IC21x = 13097785029974667218569852229612012876198611075921474226062631058823487472039;
    uint256 constant IC21y = 14523585485831615390648403280015252312841004062772114734109164337346197745926;
    
    uint256 constant IC22x = 16641857159519051071067633760608523360858114161776721305536126665224733182396;
    uint256 constant IC22y = 1281050510795147757043950670046867667014400163245176423901855885779257699740;
    
    uint256 constant IC23x = 17204173385897461950720378912868725368343515696214937356155398994280819613626;
    uint256 constant IC23y = 14414548447474946721412349784971413041465097655798729235969789598067945771203;
    
    uint256 constant IC24x = 16300321355146680762310455417513953211392476401374679301353480165390377086422;
    uint256 constant IC24y = 11423935566837656526994297372287968798640921399823143503794690535706302307557;
    
    uint256 constant IC25x = 5355993804372628839435566648177417257283420040220966952422451234848340188948;
    uint256 constant IC25y = 8185486846044038155874306591498227739076792512493421781775109121348163724347;
    
    uint256 constant IC26x = 21232231122878470721640613785128144993088536241265788237618349249679970864316;
    uint256 constant IC26y = 18506328405236794449917670425022989374336500346330023271198001585071608219562;
    
    uint256 constant IC27x = 18177593604826131058666666894976403284391230640265578621533864179972235746337;
    uint256 constant IC27y = 18360435310417761356500903302137564913076057206074863193085791689027593158926;
    
    uint256 constant IC28x = 14493191928463583078044267562329950247604542097929543031110490217201324248838;
    uint256 constant IC28y = 7594897577142635342278782595994512136810609257043775521691788001759507352779;
    
    uint256 constant IC29x = 6974212725050106472844577035621092056956989671780365804438276494566800002190;
    uint256 constant IC29y = 6603033350695309262411423050542750769293265018861852189508741117531179310875;
    
    uint256 constant IC30x = 155482513597040616086460706973882605088778358072329091513001229602610494086;
    uint256 constant IC30y = 6325748630195378917661049707768130774811686724912720750615199065313159270811;
    
    uint256 constant IC31x = 21505352794996465952580810971892313435883256999098480101188168142229636498795;
    uint256 constant IC31y = 13967379389108463968897436262004144793280256220191447117548292654574321867111;
    
    uint256 constant IC32x = 21445470176480497454821190006444101097244399541084410870525346797082593750976;
    uint256 constant IC32y = 21471409109471829557907892750985897284763444989202134607143035484854896780548;
    
    uint256 constant IC33x = 20315683550169132267348462314779474919995819567071072446483015923521311531984;
    uint256 constant IC33y = 13217353155617911696106814689376757111666520772039753538823832813396923318374;
    
    uint256 constant IC34x = 9780117121830058105602775721419990297877044246055916799691422751616803289848;
    uint256 constant IC34y = 11337193623139196089246075461326379656759418604675837197824841083716266719034;
    
    uint256 constant IC35x = 11543613134622276748036346896947257292915959855210770256289096106744526823868;
    uint256 constant IC35y = 19940427538505275104995817648438690856199776269486998920965574980611060784270;
    
    uint256 constant IC36x = 10834956808250842861106204125590028353836430460810920080832506177095632317245;
    uint256 constant IC36y = 18587417262947583281165754864083183208967401263112677293426781630583135226239;
    
    uint256 constant IC37x = 14792196425063061899243885071101804252886122572619155505897487017763857476141;
    uint256 constant IC37y = 361998213211890944800827240450919439949086165652899185878022439924469795431;
    
    uint256 constant IC38x = 19054781619639083462861225574185683445019144461882914286595156845946553584078;
    uint256 constant IC38y = 8734998513836092062513552743666356226854133863946763196838078667202778768976;
    
    uint256 constant IC39x = 15040185460039109278459718886891854816228296517438362841983638531734546770242;
    uint256 constant IC39y = 10301165552452619867556161653807623059422794573334204304088111972912729963862;
    
    uint256 constant IC40x = 19110403596712415734509196789088527310827086356814952781217571241657872955537;
    uint256 constant IC40y = 4372730046526592136755272084713619582437033698711062587041955524197068385694;
    
    uint256 constant IC41x = 6806457294801366137870573905643366249188517416021371338933794683520600070967;
    uint256 constant IC41y = 9966366651562574522426859761039794076064870559073296121746732606602215493043;
    
    uint256 constant IC42x = 10513802241667863045737677367818376864717853980792445985980943466515552703168;
    uint256 constant IC42y = 4864772899631809195765370918536377014903983250958075667729819387477825361895;
    
    uint256 constant IC43x = 16611015031440387364006916145976847507352042105229956897657858474842579614708;
    uint256 constant IC43y = 6447458982776254083065573481425689511761329947591887988796138661001644698460;
    
    uint256 constant IC44x = 12185689071711467874914984791108042013273985165955438812587975891848464680708;
    uint256 constant IC44y = 16646804419680557300337041249414381747440601955487643565901197571433961885284;
    
    uint256 constant IC45x = 4216802365877802972476293586238658613104593223136735069981984214798196367235;
    uint256 constant IC45y = 7522244611516662856150398545388499673468979225809064243709421926691120250657;
    
    uint256 constant IC46x = 4034418912209873914755764643392375547647862665464223478590069024853130154397;
    uint256 constant IC46y = 15088035545796426178292915444821124438581292508847602470263798144944126672851;
    
    uint256 constant IC47x = 15310605575511453718597268110404009418341689003542583170238881668630802216905;
    uint256 constant IC47y = 18185760377016064277357564263809786597656609051755026034160348717817794006089;
    
    uint256 constant IC48x = 13889278427293369631925578463866955872513724137256770666032157648127761076224;
    uint256 constant IC48y = 16046745375682117683335837933455990948038131082304209915469041849264254157410;
    
    uint256 constant IC49x = 16364121512517738734370669636794183714745909692935023334307417261243161205974;
    uint256 constant IC49y = 2165007539977665935734666156614574951667917136674174916274867767022060843273;
    
    uint256 constant IC50x = 6757791827153017843806053615733325138628085216593068715235498320501852598665;
    uint256 constant IC50y = 4308119485629896970692457302884448755759014617275545456855395734208806373174;
    
    uint256 constant IC51x = 20240153537401299344396123716088196226754837690022369382399362050811295261263;
    uint256 constant IC51y = 21823305330535346529606974521335807038621698410488525771393430846771906798206;
    
    uint256 constant IC52x = 9651036381445772791433370409578438761480369914350411361239264489210808770850;
    uint256 constant IC52y = 9910559593767594764200413553649060709141599819724326950677254458891815757144;
    
    uint256 constant IC53x = 13279508162832376089329847786647037502297938206336397845974215105966211071808;
    uint256 constant IC53y = 8574001302715469899684148014119481133459863676685666994346831672226499746867;
    
    uint256 constant IC54x = 1111894977177755801249356600343762396723304390360161617342499939896871759007;
    uint256 constant IC54y = 17992733413945097765536619774024421519379881930654139206144583838294820186084;
    
    uint256 constant IC55x = 20425107356529264831027787241424441958637964829580636818493957296477357154474;
    uint256 constant IC55y = 8063078265666630047639780096261875225007604874096318620923303858879184285907;
    
    uint256 constant IC56x = 7471843375699558993090753116427337223209590700650066598029879934972952253098;
    uint256 constant IC56y = 2256819942069263051667523565007986424365671409782826488405975756784795677349;
    
    uint256 constant IC57x = 14760534540501031933630479770503794699853776406443671604368106738370031261120;
    uint256 constant IC57y = 6365452565992902339216491790487191678382197621700021075081633478791952727107;
    
    uint256 constant IC58x = 1167490554802326840298640665427002832866204245059906770781726581197518048271;
    uint256 constant IC58y = 19429005935452577496962217759708261204182904981933811238049556140543196858670;
    
    uint256 constant IC59x = 9641704821245441011265279663852617751953483421259390082648302096467478093655;
    uint256 constant IC59y = 16634061669128702260151429716177378982930477543769080745136893361357391269266;
    
    uint256 constant IC60x = 8428685045460828226423449603532343399665751602053662871210277209390921919054;
    uint256 constant IC60y = 15541987474525521198671599027731028112685277831819505685510139317179596094475;
    
    uint256 constant IC61x = 16509707571701120566167810436565051915569980945819696049225323612030224966195;
    uint256 constant IC61y = 16835997024570139170437993098913445040161318782560148075463452222108219653600;
    
    uint256 constant IC62x = 5536095056223457191904914002496498619301023433433048416715743883678062415020;
    uint256 constant IC62y = 8718756751122999263958000651164314898309092648654280138693873847325741143657;
    
    uint256 constant IC63x = 5814472993519901251998383693449819950009889995858301762477823801604603534056;
    uint256 constant IC63y = 10152299960730334881966268061232233190963889996719804999787258371803166517535;
    
    uint256 constant IC64x = 10585036481478052895656015826939475189532459130226317424617857215352653952445;
    uint256 constant IC64y = 21378572151476872146096510897369939060590262720343937135242662723885342936898;
    
    uint256 constant IC65x = 3744189896813618661789745100528983239609575804805360193836497079254549139109;
    uint256 constant IC65y = 8433181951323666363628503889884310839086808132802080135215931198258601210559;
    
    uint256 constant IC66x = 5508237267550354737446223970090296035608434477413475543910923992101134258835;
    uint256 constant IC66y = 18364840212464373140578869767147212321922002586018631774511907755655862607464;
    
    uint256 constant IC67x = 10059157500469225494455532839515698754146498774182308486660149434160335504801;
    uint256 constant IC67y = 1197787380970896085905885799034099745558321852615261040283830817602884923102;
    
 
    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant pLastMem = 896;

    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[67] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }
            
            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                
                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                
                g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                
                g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                
                g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                
                g1_mulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                
                g1_mulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                
                g1_mulAccC(_pVk, IC11x, IC11y, calldataload(add(pubSignals, 320)))
                
                g1_mulAccC(_pVk, IC12x, IC12y, calldataload(add(pubSignals, 352)))
                
                g1_mulAccC(_pVk, IC13x, IC13y, calldataload(add(pubSignals, 384)))
                
                g1_mulAccC(_pVk, IC14x, IC14y, calldataload(add(pubSignals, 416)))
                
                g1_mulAccC(_pVk, IC15x, IC15y, calldataload(add(pubSignals, 448)))
                
                g1_mulAccC(_pVk, IC16x, IC16y, calldataload(add(pubSignals, 480)))
                
                g1_mulAccC(_pVk, IC17x, IC17y, calldataload(add(pubSignals, 512)))
                
                g1_mulAccC(_pVk, IC18x, IC18y, calldataload(add(pubSignals, 544)))
                
                g1_mulAccC(_pVk, IC19x, IC19y, calldataload(add(pubSignals, 576)))
                
                g1_mulAccC(_pVk, IC20x, IC20y, calldataload(add(pubSignals, 608)))
                
                g1_mulAccC(_pVk, IC21x, IC21y, calldataload(add(pubSignals, 640)))
                
                g1_mulAccC(_pVk, IC22x, IC22y, calldataload(add(pubSignals, 672)))
                
                g1_mulAccC(_pVk, IC23x, IC23y, calldataload(add(pubSignals, 704)))
                
                g1_mulAccC(_pVk, IC24x, IC24y, calldataload(add(pubSignals, 736)))
                
                g1_mulAccC(_pVk, IC25x, IC25y, calldataload(add(pubSignals, 768)))
                
                g1_mulAccC(_pVk, IC26x, IC26y, calldataload(add(pubSignals, 800)))
                
                g1_mulAccC(_pVk, IC27x, IC27y, calldataload(add(pubSignals, 832)))
                
                g1_mulAccC(_pVk, IC28x, IC28y, calldataload(add(pubSignals, 864)))
                
                g1_mulAccC(_pVk, IC29x, IC29y, calldataload(add(pubSignals, 896)))
                
                g1_mulAccC(_pVk, IC30x, IC30y, calldataload(add(pubSignals, 928)))
                
                g1_mulAccC(_pVk, IC31x, IC31y, calldataload(add(pubSignals, 960)))
                
                g1_mulAccC(_pVk, IC32x, IC32y, calldataload(add(pubSignals, 992)))
                
                g1_mulAccC(_pVk, IC33x, IC33y, calldataload(add(pubSignals, 1024)))
                
                g1_mulAccC(_pVk, IC34x, IC34y, calldataload(add(pubSignals, 1056)))
                
                g1_mulAccC(_pVk, IC35x, IC35y, calldataload(add(pubSignals, 1088)))
                
                g1_mulAccC(_pVk, IC36x, IC36y, calldataload(add(pubSignals, 1120)))
                
                g1_mulAccC(_pVk, IC37x, IC37y, calldataload(add(pubSignals, 1152)))
                
                g1_mulAccC(_pVk, IC38x, IC38y, calldataload(add(pubSignals, 1184)))
                
                g1_mulAccC(_pVk, IC39x, IC39y, calldataload(add(pubSignals, 1216)))
                
                g1_mulAccC(_pVk, IC40x, IC40y, calldataload(add(pubSignals, 1248)))
                
                g1_mulAccC(_pVk, IC41x, IC41y, calldataload(add(pubSignals, 1280)))
                
                g1_mulAccC(_pVk, IC42x, IC42y, calldataload(add(pubSignals, 1312)))
                
                g1_mulAccC(_pVk, IC43x, IC43y, calldataload(add(pubSignals, 1344)))
                
                g1_mulAccC(_pVk, IC44x, IC44y, calldataload(add(pubSignals, 1376)))
                
                g1_mulAccC(_pVk, IC45x, IC45y, calldataload(add(pubSignals, 1408)))
                
                g1_mulAccC(_pVk, IC46x, IC46y, calldataload(add(pubSignals, 1440)))
                
                g1_mulAccC(_pVk, IC47x, IC47y, calldataload(add(pubSignals, 1472)))
                
                g1_mulAccC(_pVk, IC48x, IC48y, calldataload(add(pubSignals, 1504)))
                
                g1_mulAccC(_pVk, IC49x, IC49y, calldataload(add(pubSignals, 1536)))
                
                g1_mulAccC(_pVk, IC50x, IC50y, calldataload(add(pubSignals, 1568)))
                
                g1_mulAccC(_pVk, IC51x, IC51y, calldataload(add(pubSignals, 1600)))
                
                g1_mulAccC(_pVk, IC52x, IC52y, calldataload(add(pubSignals, 1632)))
                
                g1_mulAccC(_pVk, IC53x, IC53y, calldataload(add(pubSignals, 1664)))
                
                g1_mulAccC(_pVk, IC54x, IC54y, calldataload(add(pubSignals, 1696)))
                
                g1_mulAccC(_pVk, IC55x, IC55y, calldataload(add(pubSignals, 1728)))
                
                g1_mulAccC(_pVk, IC56x, IC56y, calldataload(add(pubSignals, 1760)))
                
                g1_mulAccC(_pVk, IC57x, IC57y, calldataload(add(pubSignals, 1792)))
                
                g1_mulAccC(_pVk, IC58x, IC58y, calldataload(add(pubSignals, 1824)))
                
                g1_mulAccC(_pVk, IC59x, IC59y, calldataload(add(pubSignals, 1856)))
                
                g1_mulAccC(_pVk, IC60x, IC60y, calldataload(add(pubSignals, 1888)))
                
                g1_mulAccC(_pVk, IC61x, IC61y, calldataload(add(pubSignals, 1920)))
                
                g1_mulAccC(_pVk, IC62x, IC62y, calldataload(add(pubSignals, 1952)))
                
                g1_mulAccC(_pVk, IC63x, IC63y, calldataload(add(pubSignals, 1984)))
                
                g1_mulAccC(_pVk, IC64x, IC64y, calldataload(add(pubSignals, 2016)))
                
                g1_mulAccC(_pVk, IC65x, IC65y, calldataload(add(pubSignals, 2048)))
                
                g1_mulAccC(_pVk, IC66x, IC66y, calldataload(add(pubSignals, 2080)))
                
                g1_mulAccC(_pVk, IC67x, IC67y, calldataload(add(pubSignals, 2112)))
                

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))


                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)


                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F
            
            checkField(calldataload(add(_pubSignals, 0)))
            
            checkField(calldataload(add(_pubSignals, 32)))
            
            checkField(calldataload(add(_pubSignals, 64)))
            
            checkField(calldataload(add(_pubSignals, 96)))
            
            checkField(calldataload(add(_pubSignals, 128)))
            
            checkField(calldataload(add(_pubSignals, 160)))
            
            checkField(calldataload(add(_pubSignals, 192)))
            
            checkField(calldataload(add(_pubSignals, 224)))
            
            checkField(calldataload(add(_pubSignals, 256)))
            
            checkField(calldataload(add(_pubSignals, 288)))
            
            checkField(calldataload(add(_pubSignals, 320)))
            
            checkField(calldataload(add(_pubSignals, 352)))
            
            checkField(calldataload(add(_pubSignals, 384)))
            
            checkField(calldataload(add(_pubSignals, 416)))
            
            checkField(calldataload(add(_pubSignals, 448)))
            
            checkField(calldataload(add(_pubSignals, 480)))
            
            checkField(calldataload(add(_pubSignals, 512)))
            
            checkField(calldataload(add(_pubSignals, 544)))
            
            checkField(calldataload(add(_pubSignals, 576)))
            
            checkField(calldataload(add(_pubSignals, 608)))
            
            checkField(calldataload(add(_pubSignals, 640)))
            
            checkField(calldataload(add(_pubSignals, 672)))
            
            checkField(calldataload(add(_pubSignals, 704)))
            
            checkField(calldataload(add(_pubSignals, 736)))
            
            checkField(calldataload(add(_pubSignals, 768)))
            
            checkField(calldataload(add(_pubSignals, 800)))
            
            checkField(calldataload(add(_pubSignals, 832)))
            
            checkField(calldataload(add(_pubSignals, 864)))
            
            checkField(calldataload(add(_pubSignals, 896)))
            
            checkField(calldataload(add(_pubSignals, 928)))
            
            checkField(calldataload(add(_pubSignals, 960)))
            
            checkField(calldataload(add(_pubSignals, 992)))
            
            checkField(calldataload(add(_pubSignals, 1024)))
            
            checkField(calldataload(add(_pubSignals, 1056)))
            
            checkField(calldataload(add(_pubSignals, 1088)))
            
            checkField(calldataload(add(_pubSignals, 1120)))
            
            checkField(calldataload(add(_pubSignals, 1152)))
            
            checkField(calldataload(add(_pubSignals, 1184)))
            
            checkField(calldataload(add(_pubSignals, 1216)))
            
            checkField(calldataload(add(_pubSignals, 1248)))
            
            checkField(calldataload(add(_pubSignals, 1280)))
            
            checkField(calldataload(add(_pubSignals, 1312)))
            
            checkField(calldataload(add(_pubSignals, 1344)))
            
            checkField(calldataload(add(_pubSignals, 1376)))
            
            checkField(calldataload(add(_pubSignals, 1408)))
            
            checkField(calldataload(add(_pubSignals, 1440)))
            
            checkField(calldataload(add(_pubSignals, 1472)))
            
            checkField(calldataload(add(_pubSignals, 1504)))
            
            checkField(calldataload(add(_pubSignals, 1536)))
            
            checkField(calldataload(add(_pubSignals, 1568)))
            
            checkField(calldataload(add(_pubSignals, 1600)))
            
            checkField(calldataload(add(_pubSignals, 1632)))
            
            checkField(calldataload(add(_pubSignals, 1664)))
            
            checkField(calldataload(add(_pubSignals, 1696)))
            
            checkField(calldataload(add(_pubSignals, 1728)))
            
            checkField(calldataload(add(_pubSignals, 1760)))
            
            checkField(calldataload(add(_pubSignals, 1792)))
            
            checkField(calldataload(add(_pubSignals, 1824)))
            
            checkField(calldataload(add(_pubSignals, 1856)))
            
            checkField(calldataload(add(_pubSignals, 1888)))
            
            checkField(calldataload(add(_pubSignals, 1920)))
            
            checkField(calldataload(add(_pubSignals, 1952)))
            
            checkField(calldataload(add(_pubSignals, 1984)))
            
            checkField(calldataload(add(_pubSignals, 2016)))
            
            checkField(calldataload(add(_pubSignals, 2048)))
            
            checkField(calldataload(add(_pubSignals, 2080)))
            
            checkField(calldataload(add(_pubSignals, 2112)))
            

            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
             return(0, 0x20)
         }
     }
 }
