/** Gas per action, recorded from receipts during the run and rendered into GAS.md at teardown. */

import { appendFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { E2E_DIR } from './infra.js';

const GAS_DIR = path.join(E2E_DIR, '.gas');
const RECORDS = path.join(GAS_DIR, 'records.jsonl');

export interface GasRecord {
  action: string;
  params: string;
  via: string;
  gasUsed: string;
}

export function resetGas(): void {
  rmSync(GAS_DIR, { recursive: true, force: true });
  mkdirSync(GAS_DIR, { recursive: true });
}

export function recordGas(action: string, params: string, via: string, gasUsed: bigint): void {
  mkdirSync(GAS_DIR, { recursive: true });
  const rec: GasRecord = { action, params, via, gasUsed: gasUsed.toString() };
  appendFileSync(RECORDS, `${JSON.stringify(rec)}\n`);
}

const ORDER = [
  'createCeremony',
  'addInvites',
  'join',
  'closeRegistration',
  'closeRegistrationScheduled',
  'deal',
  'finalize',
  'abort',
  'openDecryption',
  'allowAdapter',
  'authorizeCreator',
  'bindProcess',
  'submitRequest',
  'submitPartial',
  'publishPartialData',
  'combine',
  'newProcess (council)',
  'requestResultsDecryption',
  'finalizeResultsFromDKG',
];

const fmt = (v: number): string => Math.round(v).toLocaleString('en-US');

export function renderGasMarkdown(meta: { anvil: string }): string | undefined {
  if (!existsSync(RECORDS)) return undefined;
  const records = readFileSync(RECORDS, 'utf8')
    .split('\n')
    .filter((l) => l.trim() !== '')
    .map((l) => JSON.parse(l) as GasRecord);
  if (records.length === 0) return undefined;
  const groups = new Map<string, { action: string; params: string; via: Set<string>; gas: number[] }>();
  for (const r of records) {
    const key = `${r.action}\u0000${r.params}`;
    const g = groups.get(key) ?? { action: r.action, params: r.params, via: new Set<string>(), gas: [] };
    g.via.add(r.via);
    g.gas.push(Number(r.gasUsed));
    groups.set(key, g);
  }
  const rows = [...groups.values()].sort((a, b) => {
    const oa = ORDER.indexOf(a.action);
    const ob = ORDER.indexOf(b.action);
    if (oa !== ob) return (oa < 0 ? 99 : oa) - (ob < 0 ? 99 : ob);
    return a.params.localeCompare(b.params, 'en', { numeric: true });
  });
  const lines = [
    '# Council gas per action (measured)',
    '',
    'Generated by the headless e2e suite (`tests/`, `pnpm --filter ./tests test`) from transaction',
    'receipts: real Groth16 verifiers (development phase-2 setup), real proofs, every action on',
    `${meta.anvil}. Regenerated on every full run; do not edit by hand.`,
    '',
    '`gasUsed` includes the 21,000 intrinsic gas and calldata. `bindProcess`/`submitRequest` go through',
    'the test adapter (`MockCouncilAdapter`), so they include its small forwarding overhead.',
    'The last three rows are the DAVINCI round-trip on a davinci-contracts `ProcessRegistry`',
    '(`tests/davinci.test.ts`): `newProcess` binds through the real `CouncilAdapter`, and',
    '`requestResultsDecryption` includes its `submitRequest` (two subgroup checks per active field).',
    '',
    '| Action | Parameters | Gas (mean) | Min | Max | Samples | Sent via |',
    '|---|---|---:|---:|---:|---:|---|',
  ];
  for (const g of rows) {
    const mean = g.gas.reduce((s, v) => s + v, 0) / g.gas.length;
    lines.push(
      `| ${g.action} | ${g.params.replace(/\|/g, '\\|') || '–'} | ${fmt(mean)} | ${fmt(Math.min(...g.gas))} | ${fmt(Math.max(...g.gas))} | ${g.gas.length} | ${[...g.via].sort().join(', ')} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Write the table. The committed GAS.md is only replaced by a run that measured every action
 * (a full suite run); partial runs write `.gas/GAS.md`.
 */
export function writeGasMarkdown(meta: { anvil: string }): void {
  const md = renderGasMarkdown(meta);
  if (!md) return;
  const seen = new Set(
    readFileSync(RECORDS, 'utf8')
      .split('\n')
      .filter((l) => l.trim() !== '')
      .map((l) => (JSON.parse(l) as GasRecord).action),
  );
  const complete = ORDER.every((a) => seen.has(a));
  writeFileSync(complete ? path.join(E2E_DIR, 'GAS.md') : path.join(GAS_DIR, 'GAS.md'), md);
}
