// SPDX-License-Identifier: AGPL-3.0-or-later
// Vendored from github.com/vocdoni/davinci-dkg, solidity/src/libraries/BabyJubJub.sol at commit
// 6d02bf1fe68f3aa1610f2dabaf0def3545428089 (the NI-DKG's on-chain BabyJubJub library), byte for
// byte below this header. Council uses it read-only through CouncilCurve.sol; do not edit it here.
// Take fixes from upstream and re-vendor the whole file instead.
pragma solidity 0.8.28;

/// @title BabyJubJub
/// @notice Twisted Edwards elliptic curve arithmetic over the BN254 scalar field
///         in the REDUCED form (A = -1) used by gnark-crypto's
///         `bn254/twistededwards` curve and by the davinci-dkg ZK circuits.
///         Originally adapted from https://github.com/yondonfu/sol-baby-jubjub
///         (MIT) — that implementation used the iden3/circomlib chart
///         (A = 168700, D = 168696) and affine coordinates. It was switched to
///         the reduced chart because contributions emit `commitment0X/Y` in
///         reduced form (`group.Encode(...)` -> gnark `PointAffine`), and the
///         on-chain accumulator must use the same chart or the resulting point
///         is meaningless in either form.
///
/// Curve equation: a·x² + y² = 1 + d·x²·y²
///   a = -1 (encoded as Q - 1)
///   d = 12181644023421730124874158521699555681764249180949974110617291017600649128846
///   Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617
///       (BN254 scalar field prime)
///
/// Identity element: (0, 1)  (unchanged across the two charts).
///
/// External API (affine coordinates, `(x, y)` with `x, y ∈ [0, Q)`) is
/// unchanged; internally every group operation runs in *extended twisted
/// Edwards coordinates* `(X : Y : Z : T)` with `x = X/Z`, `y = Y/Z`,
/// `T = X·Y/Z` (Hisil, Wong, Carter, Dawson, "Twisted Edwards Curves
/// Revisited", ASIACRYPT 2008, §3; the same coordinates RFC 8032 §5.1.4
/// prescribes for Ed25519). Addition and doubling are inversion-free and a
/// single modular inversion (bigModExp) is paid when converting the final
/// result back to affine — or none at all when the result is only compared
/// against an affine point, as in `verifySchnorrEquation` and
/// `isInPrimeSubgroup`.
///
/// The addition formula used (HWCD §3.1, EFD "add-2008-hwcd-3", specialised
/// to a = -1 with k = 2·d) is the projective form of the affine law
///   x3 = (x1·y2 + y1·x2) / (1 + d·x1·x2·y1·y2)
///   y3 = (y1·y2 - a·x1·x2) / (1 - d·x1·x2·y1·y2)
/// which is *complete* on this curve: a = -1 is a square and d is a
/// non-square in F_Q (d^((Q-1)/2) ≡ -1), so by Bernstein–Birkner–Joye–
/// Lange–Peters ("Twisted Edwards Curves", 2008, Thm. 3.3) both denominators
/// are non-zero for every pair of curve points, including P + P, P + (-P)
/// and additions involving the identity or the small-order (cofactor)
/// points. No case distinctions are therefore needed in the group law.
library BabyJubJub {
    error NotCanonical();
    error NotOnCurve();
    error IsIdentity();
    error NotInPrimeSubgroup();

    /// @dev BN254 scalar field prime Q
    uint256 internal constant Q =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev Curve parameter a = -1 (mod Q)
    uint256 internal constant A =
        21888242871839275222246405745257275088548364400416034343698204186575808495616;
    /// @dev Curve parameter d (reduced-form value matching gnark BabyJubJub)
    uint256 internal constant D =
        12181644023421730124874158521699555681764249180949974110617291017600649128846;
    /// @dev 2·d mod Q — the constant `k` of the a = -1 extended addition
    ///      formula (HWCD 2008 §3.1). Pinned by `test_TwoDConstant`.
    uint256 internal constant TWO_D =
        2475045175004185027501911298141836274980133961483913877536377848625489762075;

    /// @dev Generator point X coordinate (gnark canonical reduced form).
    uint256 internal constant GENERATOR_X =
        9671717474070082183213120605117400219616337014328744928644933853176787189663;
    /// @dev Generator point Y coordinate (gnark canonical reduced form).
    uint256 internal constant GENERATOR_Y =
        16950150798460657717958625567821834550301663161624707787222815936182638968203;
    /// @dev Subgroup (prime-order) cardinality. The full curve has 8·L points;
    ///      the prime-order subgroup generated by `(GENERATOR_X, GENERATOR_Y)`
    ///      has order `SUBGROUP_ORDER`. Scalars for `scalarMul` should be
    ///      reduced mod this value.
    uint256 internal constant SUBGROUP_ORDER =
        2736030358979909402780800718157159386076813972158567259200215660948447373041;
    /// @dev Cofactor h = 8.
    uint256 internal constant COFACTOR = 8;

    // ─── Point validation ──────────────────────────────────────────────────────

    /// @notice Test whether `(x, y)` satisfies the twisted-Edwards equation
    ///         `a·x² + y² = 1 + d·x²·y²` with `a = -1`.
    /// @dev    Pure (no precompile use). Returns true for the identity (0, 1)
    ///         and false for non-canonical encodings (coordinate >= Q).
    function isOnCurve(uint256 x, uint256 y) internal pure returns (bool) {
        if (x >= Q || y >= Q) return false;
        uint256 x2 = mulmod(x, x, Q);
        uint256 y2 = mulmod(y, y, Q);
        // lhs = a·x² + y² = (Q - x²) + y² (mod Q)  (since a = -1)
        uint256 lhs = addmod(Q - x2, y2, Q);
        // rhs = 1 + d·x²·y²
        uint256 rhs = addmod(1, mulmod(D, mulmod(x2, y2, Q), Q), Q);
        return lhs == rhs;
    }

    /// @notice Whether the encoding is canonical: both coordinates lie in [0, Q).
    function isCanonical(uint256 x, uint256 y) internal pure returns (bool) {
        return x < Q && y < Q;
    }

    /// @notice Whether `(x, y)` is the identity element (0, 1).
    function isIdentity(uint256 x, uint256 y) internal pure returns (bool) {
        return x == 0 && y == 1;
    }

    /// @notice Whether `(x, y)` lies in the prime-order subgroup.
    /// @dev    Implemented as `[L]P == identity` via a width-2 windowed
    ///         double-and-add (MSB-first) over the bits of `L`. We walk
    ///         `L` directly — `scalarMul` reduces its scalar mod `L`
    ///         first, which would short-circuit `[L]P` to `[0]P` and
    ///         render the check vacuous. Non-canonical or off-curve inputs
    ///         are rejected up front (the group law is only complete for
    ///         points of the curve). Use only at entry points where
    ///         prime-subgroup membership is not otherwise enforced.
    function isInPrimeSubgroup(uint256 x, uint256 y) internal pure returns (bool) {
        if (x == 0 && y == 1) return true; // identity is in every subgroup
        if (!isOnCurve(x, y)) return false; // also rejects x, y >= Q
        return _isIdentity(_mulWindow2(SUBGROUP_ORDER, x, y));
    }

    /// @notice Validate that `(x, y)` is a canonical, on-curve, non-identity
    ///         point on BabyJubJub. Reverts with one of `NotCanonical`,
    ///         `NotOnCurve`, or `IsIdentity` on failure.
    /// @dev    Does NOT enforce prime-subgroup membership; see
    ///         `isInPrimeSubgroup` for that check. Callers that need the
    ///         stronger guarantee (i.e. those that do not separately prove
    ///         knowledge of a discrete log) should additionally call
    ///         `isInPrimeSubgroup`.
    function requireValidPoint(uint256 x, uint256 y) internal pure {
        if (!isCanonical(x, y)) revert NotCanonical();
        if (x == 0 && y == 1) revert IsIdentity();
        if (!isOnCurve(x, y)) revert NotOnCurve();
    }

    // ─── Affine group operations ───────────────────────────────────────────────

    /// @notice Add two points on the Baby JubJub curve (affine in, affine out).
    /// @dev    One extended-coordinate addition plus one modular inversion
    ///         for the conversion back to affine. The formula is complete
    ///         (see the library notice), so P + P, P + (-P) and the identity
    ///         need no special handling; the identity shortcuts below only
    ///         save the inversion.
    /// @param _x1 x-coordinate of point P1
    /// @param _y1 y-coordinate of point P1
    /// @param _x2 x-coordinate of point P2
    /// @param _y2 y-coordinate of point P2
    /// @return x3 x-coordinate of P1 + P2
    /// @return y3 y-coordinate of P1 + P2
    function pointAdd(
        uint256 _x1,
        uint256 _y1,
        uint256 _x2,
        uint256 _y2
    ) internal view returns (uint256 x3, uint256 y3) {
        // Identity shortcuts: (0,1) is the neutral element
        if (_x1 == 0 && _y1 == 1) {
            return (_x2, _y2);
        }
        if (_x2 == 0 && _y2 == 1) {
            return (_x1, _y1);
        }
        Field memory fq = _field();
        ExtPoint memory p = _fromAffine(_x1, _y1, fq);
        ExtPoint memory q = _fromAffine(_x2, _y2, fq);
        _add(p, p, q, fq);
        return _toAffine(p);
    }

    /// @notice Point doubling: P + P (affine in, affine out).
    /// @dev    Uses the dedicated extended-coordinate doubling formula
    ///         (HWCD 2008 §3.3, "dbl-2008-hwcd"), which is valid for every
    ///         point of the curve, then one inversion to return to affine.
    function pointDouble(uint256 x, uint256 y)
        internal
        view
        returns (uint256, uint256)
    {
        Field memory fq = _field();
        ExtPoint memory p = _fromAffine(x, y, fq);
        _double(p, p, fq);
        return _toAffine(p);
    }

    /// @notice Scalar multiplication `[s] (x, y)` on BabyJubJub.
    /// @dev    The scalar is reduced modulo `SUBGROUP_ORDER` first; this is
    ///         sound for points in the prime-order subgroup (every honest
    ///         call site). The multiplication itself is a width-2 windowed
    ///         double-and-add in extended coordinates (see `_mulWindow2`)
    ///         followed by a single inversion.
    ///
    ///         Cost: ~`bitlen(s % L)` doublings + ~`bitlen/2 · 3/4`
    ///         additions, each a handful of `mulmod`s, plus one bigModExp.
    function scalarMul(uint256 s, uint256 x, uint256 y)
        internal
        view
        returns (uint256, uint256)
    {
        uint256 k = s % SUBGROUP_ORDER;
        if (k == 0) return (0, 1); // identity
        return _toAffine(_mulWindow2(k, x, y));
    }

    /// @notice Convenience: `[s] · G` where G is the canonical generator.
    function scalarMulBase(uint256 s) internal view returns (uint256, uint256) {
        return scalarMul(s, GENERATOR_X, GENERATOR_Y);
    }

    // ─── Schnorr verification (optimised) ──────────────────────────────────────

    /// @dev Precomputed [2] · G in reduced twisted-Edwards coordinates, used
    ///      by the windowed Strauss–Shamir verifier below. Computed once
    ///      off-chain and inlined as a constant so we never pay for a
    ///      per-call doubling of G.
    uint256 private constant TWO_G_X =
        6181589843805936102166733432625702983249926793164243794170119559257043191516;
    uint256 private constant TWO_G_Y =
        633281375905621697187330766174974863687049529291089048651929454608812697683;

    /// @dev Precomputed [3] · G.
    uint256 private constant THREE_G_X =
        8787197234602503388844295997017788867392848147420327174860413988187367696532;
    uint256 private constant THREE_G_Y =
        15305195750036305661220525648961313310481046260814497672243197092298550508693;

    /// @notice Verify the Schnorr response equation `z · G == A + c · PK`
    ///         using a width-2 windowed Strauss–Shamir double scalar
    ///         multiplication on the basis `(G, -PK)`.
    /// @dev    Equivalent (in TE arithmetic) to `z · G + c · (-PK) == A`,
    ///         which we evaluate as a single double-and-add over 2-bit
    ///         windows of `z` and `c` simultaneously. Per-window cost is
    ///         two doublings + at most one addition against a 16-entry
    ///         precomputed table `T[i][j] = i·G + j·(-PK)` for
    ///         `i, j ∈ {0, 1, 2, 3}`. Multiples of `G` are compile-time
    ///         constants; multiples of `-PK` and the cross terms are
    ///         built once at the top of the call (13 group additions).
    ///         Everything runs in extended coordinates and the final
    ///         comparison against `A` is done projectively, so the whole
    ///         verification performs no modular inversion at all.
    ///
    ///         Sound for `pk` in the prime-order subgroup. The Schnorr
    ///         verification path satisfies that requirement: any prover
    ///         that can produce a valid `(A, z)` already knows a discrete
    ///         log of `pk` to base `G`, so `pk` lies in `<G>`. Non-canonical
    ///         encodings of `A` or `PK` (coordinate >= Q) never verify.
    /// @param  z   Schnorr response scalar (will be reduced mod L).
    /// @param  c   Fiat–Shamir challenge scalar (will be reduced mod L).
    /// @param  ax  X coordinate of the Schnorr nonce point A.
    /// @param  ay  Y coordinate of A.
    /// @param  pkx X coordinate of the prover's public key PK.
    /// @param  pky Y coordinate of PK.
    function verifySchnorrEquation(
        uint256 z,
        uint256 c,
        uint256 ax,
        uint256 ay,
        uint256 pkx,
        uint256 pky
    ) internal pure returns (bool) {
        if (!isCanonical(ax, ay) || !isCanonical(pkx, pky)) return false;
        z = z % SUBGROUP_ORDER;
        c = c % SUBGROUP_ORDER;

        // -PK on twisted Edwards: (Q - x, y). The identity (0, 1) negates to
        // itself; honest paths reject identity at point validation, so the
        // branch is for completeness rather than a hot path.
        uint256 npkx = pkx == 0 ? 0 : Q - pkx;

        // Build the lookup table T[i][j] = i·G + j·(-PK), i,j ∈ {0,1,2,3},
        // in extended coordinates at tbl[i*4 + j]. Slot 0 (i = j = 0) is the
        // identity (0 : 1 : 1 : 0).
        Field memory fq = _field();
        ExtPoint[16] memory tbl;
        tbl[0].y = 1;
        tbl[0].z = 1;
        // T[i][0] = i·G  (constants for i ≥ 1)
        _setAffine(tbl[4], GENERATOR_X, GENERATOR_Y, fq);
        _setAffine(tbl[8], TWO_G_X, TWO_G_Y, fq);
        _setAffine(tbl[12], THREE_G_X, THREE_G_Y, fq);
        // T[0][1] = -PK, T[0][2] = 2·(-PK), T[0][3] = 3·(-PK)
        _setAffine(tbl[1], npkx, pky, fq);
        _double(tbl[2], tbl[1], fq);
        _add(tbl[3], tbl[2], tbl[1], fq);
        // T[i][j] = i·G + j·(-PK) for the 9 cross terms. Complete addition
        // keeps these correct even when PK is a small multiple of G and a
        // cross term collapses to the identity (e.g. G + (-G)).
        for (uint256 i = 4; i <= 12; i += 4) {
            for (uint256 j = 1; j < 4; j++) {
                _add(tbl[i + j], tbl[i], tbl[j], fq);
            }
        }

        // Walk the 2-bit windows of z and c MSB-first. Scalars are < 2^252
        // after reduction, so windows 0..125 cover them. Leading windows
        // that are zero in both scalars cost nothing: the accumulator is
        // only initialised (copied from the table) on the first non-zero
        // window, and doubled from then on. If every window is zero
        // (z ≡ c ≡ 0 mod L) the accumulator stays the identity.
        ExtPoint memory acc = ExtPoint(0, 1, 1, 0);
        bool started;
        for (uint256 shift = 252; shift > 0;) {
            uint256 idx;
            unchecked {
                shift -= 2;
                idx = (((z >> shift) & 3) << 2) | ((c >> shift) & 3);
            }
            if (started) {
                _double(acc, acc, fq);
                _double(acc, acc, fq);
                if (idx != 0) _add(acc, acc, tbl[idx], fq);
            } else if (idx != 0) {
                _copy(acc, tbl[idx]);
                started = true;
            }
        }
        return _equalsAffine(acc, ax, ay);
    }

    // ─── Extended twisted-Edwards coordinates (private) ────────────────────────
    //
    // Formulas: Hisil–Wong–Carter–Dawson, "Twisted Edwards Curves Revisited",
    // ASIACRYPT 2008 (EFD entries add-2008-hwcd-3 and dbl-2008-hwcd), as also
    // specified in RFC 8032 §5.1.4 for the a = -1 Ed25519 curve.
    //
    // Points are passed as memory structs (one stack slot each) and results
    // are written in place; every operation reads all of its inputs before
    // writing, so the output may alias either input (`_add(p, p, q, fq)`).
    // All coordinates are kept in [0, Q): every stored value is the output
    // of mulmod/addmod and affine inputs are reduced in `_setAffine`, which
    // is what makes the unchecked subtractions `q - x` below valid.

    /// @dev A point in extended coordinates (X : Y : Z : T) with x = X/Z,
    ///      y = Y/Z, T = X·Y/Z and Z ≠ 0. The identity is (0 : 1 : 1 : 0).
    struct ExtPoint {
        uint256 x;
        uint256 y;
        uint256 z;
        uint256 t;
    }

    /// @dev Field constants handed to the group operations through memory.
    ///      Each operation references the modulus ~20 times and, with this
    ///      project's size-oriented optimizer settings (`optimizer_runs = 1`),
    ///      solc materialises every use of a 32-byte literal through a
    ///      ~40-gas `codecopy` sequence. Loading it from memory into a stack
    ///      local once per operation costs a single `mload` instead.
    struct Field {
        uint256 q; // Q
        uint256 twoD; // TWO_D
    }

    function _field() private pure returns (Field memory) {
        return Field(Q, TWO_D);
    }

    /// @dev Set `r` to the affine point (x, y): (x : y : 1 : x·y), reducing
    ///      the coordinates mod Q.
    function _setAffine(ExtPoint memory r, uint256 x, uint256 y, Field memory fq) private pure {
        uint256 q = fq.q;
        r.x = x % q;
        r.y = y % q;
        r.z = 1;
        r.t = mulmod(r.x, r.y, q);
    }

    /// @dev Allocate a fresh extended point from affine coordinates.
    function _fromAffine(uint256 x, uint256 y, Field memory fq)
        private
        pure
        returns (ExtPoint memory r)
    {
        r = ExtPoint(0, 0, 0, 0);
        _setAffine(r, x, y, fq);
    }

    /// @dev r = p (field-wise copy; assigning the pointer would alias).
    function _copy(ExtPoint memory r, ExtPoint memory p) private pure {
        r.x = p.x;
        r.y = p.y;
        r.z = p.z;
        r.t = p.t;
    }

    /// @dev Convert back to affine with a single inversion of Z.
    function _toAffine(ExtPoint memory p) private view returns (uint256 x, uint256 y) {
        uint256 zInv = _inverse(p.z);
        x = mulmod(p.x, zInv, Q);
        y = mulmod(p.y, zInv, Q);
    }

    /// @dev Whether p is the identity, i.e. x = 0 and y = 1: X = 0 and
    ///      Y = Z (Z ≠ 0). Note the order-2 point (0 : -Z : Z) also has
    ///      X = 0 but Y ≠ Z.
    function _isIdentity(ExtPoint memory p) private pure returns (bool) {
        return p.x == 0 && p.y == p.z && p.z != 0;
    }

    /// @dev Whether p equals the affine point (x, y) with x, y < Q:
    ///      X = x·Z and Y = y·Z. Avoids the inversion of `_toAffine`.
    function _equalsAffine(ExtPoint memory p, uint256 x, uint256 y) private pure returns (bool) {
        return p.z != 0 && mulmod(x, p.z, Q) == p.x && mulmod(y, p.z, Q) == p.y;
    }

    /// @dev Unified addition r = p1 + p2 in extended coordinates for a = -1
    ///      (HWCD 2008 §3.1; EFD "add-2008-hwcd-3"; RFC 8032 §5.1.4), with
    ///      k = 2·d. Cost 9 mulmod. Complete on this curve (see the library
    ///      notice): valid for p1 = p2, p1 = -p2 and the identity.
    ///
    ///        A = (Y1 - X1)·(Y2 - X2)     B = (Y1 + X1)·(Y2 + X2)
    ///        C = T1·k·T2                 D = 2·Z1·Z2
    ///        E = B - A   F = D - C   G = D + C   H = B + A
    ///        X3 = E·F    Y3 = G·H    T3 = E·H    Z3 = F·G
    function _add(ExtPoint memory r, ExtPoint memory p1, ExtPoint memory p2, Field memory fq)
        private
        pure
    {
        uint256 q = fq.q;
        // Single-letter locals follow the HWCD naming above; they are
        // unrelated to the curve constants `A` and `D`. Subtractions are
        // written as `u + (q - v)` with v < q, hence unchecked. Statements
        // are grouped so that few values are live at once (cheaper stack
        // scheduling); all inputs are read before `r` is written.
        unchecked {
            uint256 a = mulmod(addmod(p1.y, q - p1.x, q), addmod(p2.y, q - p2.x, q), q);
            uint256 b = mulmod(addmod(p1.y, p1.x, q), addmod(p2.y, p2.x, q), q);
            uint256 e = addmod(b, q - a, q);
            uint256 h = addmod(b, a, q);
            uint256 c = mulmod(mulmod(p1.t, p2.t, q), fq.twoD, q);
            uint256 d = mulmod(p1.z, p2.z, q);
            d = addmod(d, d, q);
            uint256 f = addmod(d, q - c, q);
            uint256 g = addmod(d, c, q);
            r.x = mulmod(e, f, q);
            r.t = mulmod(e, h, q);
            r.y = mulmod(g, h, q);
            r.z = mulmod(f, g, q);
        }
    }

    /// @dev Doubling r = 2·p in extended coordinates for a = -1
    ///      (HWCD 2008 §3.3; EFD "dbl-2008-hwcd"; RFC 8032 §5.1.4). Cost
    ///      8 mulmod. Does not read T1 and does not involve d: it uses the
    ///      curve equation instead, and is valid for every point of the
    ///      curve.
    ///
    ///        A = X1²   B = Y1²   C = 2·Z1²   D = a·A = -A
    ///        E = (X1 + Y1)² - A - B
    ///        G = D + B = B - A   F = G - C   H = D - B = -(A + B)
    ///        X3 = E·F    Y3 = G·H    T3 = E·H    Z3 = F·G
    function _double(ExtPoint memory r, ExtPoint memory p, Field memory fq) private pure {
        uint256 q = fq.q;
        unchecked {
            uint256 e = addmod(p.x, p.y, q); // X1 + Y1
            uint256 a = mulmod(p.x, p.x, q);
            uint256 b = mulmod(p.y, p.y, q);
            uint256 ab = addmod(a, b, q);
            uint256 g = addmod(b, q - a, q);
            e = addmod(mulmod(e, e, q), q - ab, q);
            uint256 h = q - ab; // in (0, q]; only ever fed to mulmod, which reduces it
            uint256 c = mulmod(p.z, p.z, q);
            c = addmod(c, c, q);
            uint256 f = addmod(g, q - c, q);
            r.x = mulmod(e, f, q);
            r.t = mulmod(e, h, q);
            r.y = mulmod(g, h, q);
            r.z = mulmod(f, g, q);
        }
    }

    /// @dev [k]·(x, y) for a raw scalar `k` (NOT reduced mod L, so that
    ///      `isInPrimeSubgroup` can evaluate [L]·P), returned in extended
    ///      coordinates. Width-2 fixed window, MSB-first: precomputes
    ///      P, 2P, 3P and consumes two bits per iteration (two doublings
    ///      + at most one addition). Leading zero windows are skipped; for
    ///      k = 0 the identity is returned.
    function _mulWindow2(uint256 k, uint256 x, uint256 y)
        private
        pure
        returns (ExtPoint memory acc)
    {
        Field memory fq = _field();
        // tbl[m] = m·P for m ∈ {1, 2, 3}; tbl[0] is unused.
        ExtPoint[4] memory tbl;
        _setAffine(tbl[1], x, y, fq);
        _double(tbl[2], tbl[1], fq);
        _add(tbl[3], tbl[2], tbl[1], fq);

        acc = ExtPoint(0, 1, 1, 0);
        bool started;
        for (uint256 shift = 256; shift > 0;) {
            uint256 bits;
            unchecked {
                shift -= 2;
                bits = (k >> shift) & 3;
            }
            if (started) {
                _double(acc, acc, fq);
                _double(acc, acc, fq);
                if (bits != 0) _add(acc, acc, tbl[bits], fq);
            } else if (bits != 0) {
                _copy(acc, tbl[bits]);
                started = true;
            }
        }
    }

    // ─── Private helpers ───────────────────────────────────────────────────────

    /// @dev Q - 2, used as the Fermat exponent for modular inverse (a^(Q-2) mod Q).
    ///      Stored as a constant so the assembly block can reference it via mload.
    uint256 private constant Q_MINUS_2 =
        21888242871839275222246405745257275088548364400416034343698204186575808495615;

    /// @dev Modular multiplicative inverse via Fermat's little theorem.
    ///      Returns a^(Q-2) mod Q using the bigModExp precompile (0x05).
    function _inverse(uint256 _a) private view returns (uint256 o) {
        uint256 exponent = Q_MINUS_2;
        uint256 modulus = Q;
        assembly {
            let memPtr := mload(0x40)
            mstore(memPtr, 0x20)               // length of base
            mstore(add(memPtr, 0x20), 0x20)    // length of exponent
            mstore(add(memPtr, 0x40), 0x20)    // length of modulus
            mstore(add(memPtr, 0x60), _a)      // base
            mstore(add(memPtr, 0x80), exponent) // exponent = Q - 2
            mstore(add(memPtr, 0xa0), modulus)  // modulus = Q
            // bigModExp precompile at 0x05
            let success := staticcall(gas(), 0x05, memPtr, 0xc0, memPtr, 0x20)
            if iszero(success) { revert(0, 0) }
            o := mload(memPtr)
        }
    }
}
