#!/usr/bin/env bash
# DAVINCI DKG Council circuits build: compile (--O2) -> Groth16 DEV phase 2 (one local contribution + a public
# beacon) -> vkeys -> Solidity verifiers -> circuitReleaseId -> build/release.json (copied with the
# vkeys to release/) -> vectors.
#
# DEVELOPMENT SETUP — DO NOT USE IN PRODUCTION. Whoever ran the local contribution could keep its
# toxic waste and forge proofs. Production needs a multi-party phase 2 (docs/architecture.md §2).
#
# The phase-2 setup is skipped when build/<circuit>_final.zkey exists and was made from the same
# r1cs (sha256 recorded next to it); FORCE_SETUP=1 redoes it. A new setup changes the vkeys, the
# verifiers, the circuitReleaseId and invalidates the proof fixtures (pnpm run fixtures).
set -euo pipefail

cd "$(dirname "$0")"
CIRCOM="${CIRCOM:-$HOME/.local/bin/circom}"
SNARKJS="node_modules/.bin/snarkjs"
# Default under $HOME, downloaded and blake2b-verified below on first use; COUNCIL_PTAU forces any
# other 2^18 phase-1 file.
PTAU="${COUNCIL_PTAU:-$HOME/.davinci-dkg-council/ptau/powersOfTau28_hez_final_18.ptau}"
PTAU_URL="https://circom.info/powersOfTau28_hez_final_18.ptau"
# The blake2b digest snarkjs publishes for that file ("Prepared (phase2) Ptau files") — the same
# URL and digest as scripts/ci-fetch-ptau.sh (what the CI workflows use); keep the two in sync.
PTAU_BLAKE2B="7e6a9c2e5f05179ddfc923f38f917c9e6831d16922a902b0b4758b8e79c2ab8a81bb5f29952e16ee6c5067ed044d7857b5de120a90704c1d3b637fd94b95b13e"
VERIFIERS="../solidity/src/verifiers"
BEACON="${COUNCIL_DEV_BEACON:-$(printf 'davinci-dkg-council circuits-v1 dev beacon' | sha256sum | cut -d' ' -f1)}"

[ -x "$CIRCOM" ] || { echo "circom not found at $CIRCOM" >&2; exit 1; }
if [ ! -f "$PTAU" ]; then
  echo "== ptau not found at $PTAU — downloading the Hermez powersOfTau28_hez_final_18.ptau (~300 MB)"
  mkdir -p "$(dirname "$PTAU")"
  curl -fsSL --retry 2 -o "$PTAU" "$PTAU_URL"
  if ! echo "$PTAU_BLAKE2B  $PTAU" | b2sum -c -; then
    rm -f "$PTAU"
    echo "blake2b mismatch for the downloaded ptau (file removed): expected the Hermez digest" \
      "$PTAU_BLAKE2B. Point COUNCIL_PTAU at a trusted 2^18 powers-of-tau file instead." >&2
    exit 1
  fi
fi
"$CIRCOM" --version | grep -q "2.2.3" || { echo "circom 2.2.3 required" >&2; exit 1; }

mkdir -p build "$VERIFIERS"

for c in deal partial; do
  echo "== compile $c"
  "$CIRCOM" "$c.circom" --r1cs --wasm --sym --O2 -l node_modules -o build
  "$SNARKJS" r1cs info "build/$c.r1cs"

  r1cs_sha=$(sha256sum "build/$c.r1cs" | cut -d' ' -f1)
  if [ "${FORCE_SETUP:-0}" != "1" ] && [ -f "build/${c}_final.zkey" ] &&
    [ "$(cat "build/$c.setup.r1cs.sha256" 2>/dev/null)" = "$r1cs_sha" ]; then
    echo "== $c: phase-2 setup up to date (FORCE_SETUP=1 to redo)"
  else
    echo "== $c: groth16 setup (DEV)"
    "$SNARKJS" groth16 setup "build/$c.r1cs" "$PTAU" "build/${c}_0000.zkey"
    "$SNARKJS" zkey contribute "build/${c}_0000.zkey" "build/${c}_0001.zkey" \
      --name="davinci-dkg-council DEV contribution - NOT FOR PRODUCTION" -e="$(head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    "$SNARKJS" zkey beacon "build/${c}_0001.zkey" "build/${c}_final.zkey" "$BEACON" 10 \
      -n="davinci-dkg-council DEV beacon - NOT FOR PRODUCTION"
    rm -f "build/${c}_0000.zkey" "build/${c}_0001.zkey"
    echo "$r1cs_sha" >"build/$c.setup.r1cs.sha256"
  fi

  "$SNARKJS" zkey export verificationkey "build/${c}_final.zkey" "build/${c}_vkey.json"
done

echo "== verifiers"
for pair in deal:DealVerifier partial:PartialVerifier; do
  c=${pair%%:*}
  name=${pair##*:}
  out="$VERIFIERS/$name.sol"
  "$SNARKJS" zkey export solidityverifier "build/${c}_final.zkey" "build/$name.raw.sol"
  {
    head -n 1 "build/$name.raw.sol"
    echo "// Generated by circuits/build.sh from ${c}_final.zkey (snarkjs 0.7.6). Do not edit."
    echo "// DEVELOPMENT SETUP (single local contribution + beacon): NOT FOR PRODUCTION."
    tail -n +2 "build/$name.raw.sol" | sed "s/contract Groth16Verifier /contract $name /"
  } >"$out"
  grep -q "contract $name " "$out" || { echo "verifier rename failed for $out" >&2; exit 1; }
  rm -f "build/$name.raw.sol"
done

echo "== release"
COUNCIL_PTAU_FILE="$PTAU" node_modules/.bin/tsx scripts/release.ts

echo "== vectors"
node_modules/.bin/tsx scripts/gen-vectors.ts
